// (1) 관리자 현황 부스별 표 정렬  (2) 대시보드 차트 눈금·숫자 (가짜 응답)
import { chromium } from 'playwright'; import fs from 'fs';
const DIR = 'C:/dev/stamp-rally-v3/'; const src = fs.readFileSync(DIR + '원주축전_스탬프앱_3.html', 'utf8');
fs.writeFileSync(DIR + 'tests/_local.html', src.replace(/supabaseUrl: '[^']*'/, "supabaseUrl: ''").replace(/\.\/qrcode\.min\.js|\.\/jsQR\.js/g, m => '..' + m.slice(1)));
const fails = [], errs = []; const check = (n, ok, x = '') => { console.log((ok ? '  ✓ ' : '  ✗ ') + n + (x ? ' — ' + x : '')); if(!ok) fails.push(n); };
const sleep = ms => new Promise(r => setTimeout(r, ms));
const b = await chromium.launch({ channel: 'chrome' }); const p = await b.newPage({ viewport: { width: 1280, height: 900 } }); p.on('pageerror', e => errs.push(e.message));
await p.goto('file:///' + DIR + 'tests/_local.html'); await p.waitForFunction(() => S.booths.length > 0 && document.querySelector('#main'));
await p.evaluate(async () => { const d = await LocalDB._all(); const mk = (name, stamps) => { const v = { id: uuid(), name, school: '가온초', grade: '초4', gender: '여', consentedAt: Date.now(), createdAt: Date.now(), surveyAt: null, giftAt: null }; d.visitors.push(v); stamps.forEach((bid, i) => d.stamps.push({ id: uuid(), visitorId: v.id, boothId: bid, at: Date.now() - i * 60000 })); }; mk('a', ['b3', 'b10', 'b2']); mk('b', ['b3', 'b10']); mk('c', ['b3']); await LocalDB._save(d); });
await p.evaluate(() => location.hash = '#/admin'); await p.waitForSelector('#pw'); await p.fill('#pw', '1234'); await p.keyboard.press('Enter'); await p.waitForFunction(() => S.admin); await p.waitForSelector('#admBoothTbl tbody tr');
const firstN = () => p.evaluate(() => $('#admBoothTbl tbody tr .pill').textContent.trim());
const col = (i) => p.evaluate(i => $$('#admBoothTbl tbody tr').map(tr => tr.children[i].textContent.trim()), i);
check('기본: 스탬프 내림차순 (3번 부스 3개 먼저)', await firstN() === '3' && (await col(3)).slice(0, 3).join() === '3,2,1');
await p.click('#admBoothTbl th[data-k="n"]'); check('스탬프 한 번 더 → 오름차순 (0개 먼저, 3번 마지막)', (await col(3))[0] === '0' && (await col(3)).at(-1) === '3');
await p.click('#admBoothTbl th[data-k="num"]'); const nums = await col(1);
check('번호순 오름차순: 1,2,3… 숫자 먼저', nums.slice(0, 3).map(x => x.split(' ')[0]).join() === '1,2,3' && /^(본|네)/.test(nums.at(-1).split(' ')[0]));
await p.click('#admBoothTbl th[data-k="num"]'); check('번호 내림차순: 문자 번호(본·네)가 먼저', /^(본|네)/.test((await col(1))[0].split(' ')[0]));
check('정렬 표시 화살표', await p.evaluate(() => $('#admBoothTbl th.on').dataset.dir === 'desc' && $('#admBoothTbl th.on').dataset.k === 'num'));
await p.click('#admBoothTbl th[data-k="last"]'); check('최근 내림차순 → 도장 있는 부스가 위', (await col(5))[0] !== '—');
await p.evaluate(() => location.hash = '#/admin/gift'); await sleep(300); await p.evaluate(() => location.hash = '#/admin/dash'); await p.waitForSelector('#admBoothTbl tbody tr');
check('탭 갔다 와도 정렬 유지 (최근)', await p.evaluate(() => $('#admBoothTbl th.on').dataset.k === 'last'));
await p.click('#admBoothTbl tbody tr[data-bv]'); await p.waitForSelector('#bvList'); check('정렬 후에도 줄 클릭 → 명단', true); await p.evaluate(() => closeSheet());
// 대시보드 차트
const d = await b.newPage({ viewport: { width: 1400, height: 900 } }); d.on('pageerror', e => errs.push('dash ' + e.message));
const now = Date.now(), per10 = []; for(let i = 0; i < 30; i++) per10.push({ t: new Date(Math.floor((now - i * 600e3) / 600e3) * 600e3).toISOString(), n: i === 5 ? 6573 : 1200 + i * 37 });
await d.route(/rest\/v1\//, async r => { const u = r.request().url();
  if(/rpc\/admin_login/.test(u)) return r.fulfill({ contentType: 'application/json', body: 'true' });
  if(/rpc\/admin_dashboard/.test(u)) return r.fulfill({ contentType: 'application/json', body: JSON.stringify({ at: new Date().toISOString(), goal: 7, visitors: 5000, active: 4000, stamps: 30000, new_15m: 100, stamps_15m: 900, achievers: 0, survey_done: 0, gift_done: 0, gift_15m: 0, per_booth: [], per_10min: per10, per_hour: [{ h: 9, n: 12345 }, { h: 10, n: 6573 }, { h: 11, n: 800 }], by_grade: [], by_gender: [], top_schools: [], dist: [], recent: [], survey: null }) });
  if(/booths\?/.test(u)) return r.fulfill({ contentType: 'application/json', body: JSON.stringify([{ id: 'b1', number: '1', name: '테스트부스', category: 'sci', organization: '기관', zone: 'A', sort_order: 1 }]) });
  return r.fulfill({ contentType: 'application/json', body: '[]' }); });
await d.goto('file:///' + DIR + '운영대시보드.html'); await d.waitForSelector('#pw'); await d.fill('#pw', 'abcdefgh'); await d.keyboard.press('Enter'); await d.waitForSelector('#c10 svg', { timeout: 10000 });
const ticks = await d.evaluate(() => $$('#c10 .ctick').map(t => t.textContent));
check('추이: 왼쪽 눈금 (콤마)', ticks.length >= 3 && ticks.length <= 6 && ticks.some(t => t.includes(',')), ticks.join(' '));
const vals = await d.evaluate(() => $$('#c10 .cval').map(t => t.textContent));
check('추이: 값 숫자는 최고점·현재만 (2개 이하, 콤마)', vals.length <= 2 && vals.includes('6,573'), vals.join(' '));
check('추이: 막대마다 툴팁', await d.evaluate(() => $$('#c10 svg g title').length >= 30 && /~.*개/.test($('#c10 svg g title').textContent)));
const hv = await d.evaluate(() => $$('#cHour .cval').map(t => t.textContent)); const ht = await d.evaluate(() => $$('#cHour .ctick').map(t => t.textContent));
check('시간대별: 전부 콤마 표시, 눈금 만 단위 축약', hv.includes('12,345') && hv.includes('6,573') && ht.some(t => /만/.test(t)), ht.join(' '));
console.log('ERRS', errs); console.log('FAILS', fails.length ? fails : 'none'); await b.close(); fs.unlinkSync(DIR + 'tests/_local.html'); process.exit(fails.length || errs.length ? 1 : 0);
